- name: Install cron package
  package:
    name: cron
  tags: cron

- name: Install cronjobs
  template:
    src: "{{ item }}"
    dest: /etc/cron.d/
  with_fileglob: "{{ cron_config_files }}"
  tags: cron
